version: 2.1

# reusable environment for all jobs
executors:
  node-iron-executor:
    working_directory: ~/sdk-component-adapter
    docker:
      - image: cimg/node:20.13.1-browsers

# orbs
orbs:
  browser-tools: circleci/browser-tools@1.4.8

# reusable command for all jobs
commands:
  checkout_from_workspace:
    description: "To checkout and attach the workspace"
    steps:
      - checkout
      - attach_workspace:
          at: ~/sdk-component-adapter

# define jobs
jobs:
  install:
    executor: node-iron-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies & Peer Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  unit-test:
    executor: node-iron-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Linting
          command: npm run linter
      - run:
          name: Unit Test Coverage
          command: npm run test:unit -- --coverage --maxWorkers=2
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: coverage

  integration-test:
    executor: node-iron-executor
    steps:
      - checkout_from_workspace # https://discuss.circleci.com/t/cannot-checkout-anymore/46671
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Cypress Dependencies
          command: npx cypress install
      - run:
          name: Integration Test Coverage
          command: npm run test:integration:ci
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: coverage

  build:
    executor: node-iron-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  release:
    executor: node-iron-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Release
          command: npm run release

# execute the jobs in a orderly manner
workflows:
  setup_test_release:
    jobs:
      - install
      - unit-test:
          requires:
            - install
      - integration-test:
          requires:
            - install
      - build:
          requires:
            - unit-test
          filters:
            branches:
              only: master
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
